<?php

declare(strict_types=1);

use FileBridge\App;
use FileBridge\Support\Lang;

require __DIR__ . '/vendor/autoload.php';

/**
 * Web app manifest - what a browser reads when the user installs FileBridge as
 * a desktop or home screen app. Generated by PHP so the installed app carries
 * the name from config/config.php and the icons follow the release number.
 *
 * Every URL stays relative: the same file works at a domain root and in a
 * subdirectory, and `scope` then covers exactly this install.
 */
$app     = App::boot(__DIR__);
$name    = trim((string) $app->config['app_name']) ?: 'FileBridge';
$isLight = ((string) $app->config['default_theme']) === 'light';
$version = App::VERSION;

header('Content-Type: application/manifest+json; charset=utf-8');
header('Cache-Control: no-cache');

echo json_encode([
    'id'          => './',
    'lang'        => Lang::code(),
    'dir'         => 'auto',
    'name'        => $name . ' · ' . Lang::t('app.tagline'),
    'short_name'  => $name,
    'description' => Lang::t('app.description'),
    'start_url'   => './',
    'scope'       => './',
    'display'     => 'standalone',
    // Falls back left to right if the browser cannot honour the first entry.
    'display_override' => ['standalone', 'minimal-ui'],
    'orientation'      => 'any',
    // Painted before the app renders, so the window does not flash white.
    'background_color' => $isLight ? '#eef0f4' : '#0e1015',
    'theme_color'      => $isLight ? '#ffffff' : '#14171e',
    'categories'       => ['productivity', 'utilities'],
    // Reuse the window that is already open instead of starting a second one.
    'launch_handler'   => ['client_mode' => 'navigate-existing'],
    'icons' => [
        [
            'src'     => 'assets/icons/icon-192.png?v=' . $version,
            'sizes'   => '192x192',
            'type'    => 'image/png',
            'purpose' => 'any',
        ],
        [
            'src'     => 'assets/icons/icon-512.png?v=' . $version,
            'sizes'   => '512x512',
            'type'    => 'image/png',
            'purpose' => 'any',
        ],
        [
            // Full bleed artwork - Android crops this one to the launcher shape.
            'src'     => 'assets/icons/icon-maskable-512.png?v=' . $version,
            'sizes'   => '512x512',
            'type'    => 'image/png',
            'purpose' => 'maskable',
        ],
        [
            'src'   => 'assets/icons/app-icon.svg?v=' . $version,
            'sizes' => 'any',
            'type'  => 'image/svg+xml',
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
