<?php

declare(strict_types=1);

use FileBridge\App;

require __DIR__ . '/vendor/autoload.php';

/**
 * Service worker source. It lives at the app root so its scope covers the whole
 * install, and it is generated by PHP for two reasons: the cache name follows
 * the release number, and the shell file list is read from disk instead of
 * being kept in sync by hand.
 *
 * What it does NOT do matters just as much - api.php, download.php and every
 * other request pass straight through to the network. Directory listings and
 * file contents are never stored on the client.
 */
$version = App::VERSION;

// Everything the app shell needs, discovered rather than listed: adding a
// stylesheet or a module is enough for it to be precached on the next release.
$shell = ['offline.html'];
foreach (['assets/css/*.css', 'assets/js/*.js'] as $pattern) {
    foreach (glob(__DIR__ . '/' . $pattern) ?: [] as $file) {
        $shell[] = str_replace(__DIR__ . '/', '', str_replace('\\', '/', $file));
    }
}
$shell = array_map(static fn (string $path): string => $path . '?v=' . $version, $shell);

header('Content-Type: text/javascript; charset=utf-8');
header('Cache-Control: no-cache, max-age=0, must-revalidate');
?>
// FileBridge service worker - generated by sw.php, do not edit a cached copy.

const CACHE = 'filebridge-<?= $version ?>';
const VERSION = '<?= $version ?>';

// The install root, so the same worker behaves whether FileBridge is served
// from a domain root or from a subdirectory.
const HOME = new URL('./', self.location);
const BASE = HOME.href;
const ROOT = HOME.pathname;
const ASSETS = BASE + 'assets/';
const SHELL = <?= json_encode($shell, JSON_UNESCAPED_SLASHES) ?>;
const OFFLINE = BASE + 'offline.html?v=' + VERSION;

// ── install: fill the cache for this release ────────────────────────────────

self.addEventListener('install', (event) => {
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        // One file failing (a stale name, a stray 404) must not stop the whole
        // worker from installing, so these are fetched one by one.
        await Promise.all(SHELL.map(async (path) => {
            const request = new Request(BASE + path, { cache: 'reload' });
            try {
                const response = await fetch(request);
                if (response.status === 200) await cache.put(request, response);
            } catch (error) { /* offline while installing - try again next time */ }
        }));
        await self.skipWaiting();
    })());
});

// ── activate: drop the caches of older releases ─────────────────────────────

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        await Promise.all(names
            .filter((name) => name.startsWith('filebridge-') && name !== CACHE)
            .map((name) => caches.delete(name)));
        await self.clients.claim();
    })());
});

// ── fetch: static assets only ───────────────────────────────────────────────

self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // Opening the app itself: always ask the server, fall back to the offline
    // notice. Only these two URLs - download.php also arrives as a navigation
    // and must reach the browser untouched, or a large download would be
    // streamed through this worker for no reason.
    if (request.mode === 'navigate' && (url.pathname === ROOT || url.pathname === ROOT + 'index.php')) {
        event.respondWith(pageOrOffline(request));
        return;
    }

    // Only assets/ is cacheable. api.php and download.php - listings, uploads,
    // downloads, previews - are left alone on purpose.
    if (url.href.startsWith(ASSETS)) {
        event.respondWith(asset(request));
    }
});

async function pageOrOffline(request) {
    try {
        return await fetch(request);
    } catch (error) {
        const offline = await caches.match(OFFLINE);
        return offline || Response.error();
    }
}

async function asset(request) {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request);
    if (hit) return hit;

    try {
        const response = await fetch(request);
        // Only whole, same-origin responses are worth keeping.
        if (response.status === 200 && response.type === 'basic') {
            cache.put(request, response.clone());
        }
        return response;
    } catch (error) {
        // Network is gone: an older release of the same file still beats a
        // broken page, so match without the ?v= query.
        const stale = await caches.match(request, { ignoreSearch: true });
        if (stale) return stale;
        throw error;
    }
}
